### ISSUE TITLE
Image quality issues

### ISSUE THREAD

**Issue by reyaz006** [philhansen/WallpaperChanger#1]
My image is png. When setting as centered, the actual wallpaper gets noticable JPEG artifacts, even though the generated bmp file is free of them. It seems to be a minor issue of Windows 7/8 families at least.

A possible solution would be to convert images to png instead of bmp.

**Comment by philhansen** [comment]
Yes we previously discussed this issue on my blog at: http://sg20.com/techblog/2011/06/23/wallpaper-changer-command-line-utility/  My recommendation at the time was to either save it as a jpg first (using your program of choice) and/or reduce the size of the png to match your desktop.

Today I changed the code to save the wallpaper as a png instead of a bmp as you recommended.  Let's give that a try.  I'm now running Windows 10 and I tested with a few large images (jpg and png) and I couldn't see any artifacts when converting either to bmp or png.  So maybe this is no longer an issue in Windows 10?

Please let me know if you encounter any problems or still notice artifacts.  Another possible solution could be having the program resize the converted wallpaper image to match the size of the desktop.

**Comment by reyaz006** [comment]
I switched to the SetWallpaper.exe app from http://www.optimumx.com/download/

It works differently - it doesn't need to copy file anywhere, it sets exactly the needed file as wallpaper and it is reflected in the control panel - allowing me to choose any other file from the same original folder manually if needed. The app is 15 years old and it works great on my Windows 8.1, heh. It does not introduce any quality loss with my png files.

I may try WallpaperChanger again later.
