### ISSUE TITLE
[Request] Multi monitor options

### ISSUE THREAD

**Issue by pascalo7** [philhansen/WallpaperChanger#2]
Would it be possible for you to implement something so users could set what monitor they would like to change wallpaper allowing for setups with both landscape and portrait monitors to be able to have wallpapers that fit and change.

**Comment by philhansen** [comment]
The program is a simple tool that can basically do whatever Windows lets you do.  So that is Fill, Fit, Stretch, Tile, and Center.  Now on Windows 10 I see I have a new option, Span, which causes the single image to span all of the monitors.

Do you know if it is possible to set a different image for each monitor on Windows?  If not, you would probably have to try to put together all of the images into one image and then use the Span option.  But I don't know if the Span option can be made to work with monitors of different dimensions.  I have two monitors with different dimensions and it seems to zoom the image into the size of the smaller monitor (and looks bad).

If anyone knows how this can be done please share.

**Comment by pascalo7** [comment]
I'm on windows 8.1 and if you go to the wallpaper selection (desktop background) and right click one of the images it will let you set the monitor you want that image to be on, i think this is a feature on windows 10 and possibly windows 7. 
![image](https://user-images.githubusercontent.com/2935785/28500561-5bb85986-6fc2-11e7-804c-c62a7bdeedc3.png)

as the feature is in windows already would it be possible for you to implement a feature in the program to allow the user to just put the number of the monitor at the end of the command to tell the program to set the image in that location?

**Comment by philhansen** [comment]
Aha, I see now, thanks!  I'll try looking into it and let you know.

**Comment by philhansen** [comment]
Windows 8 added a new interface for setting the desktop wallpaper which allows a few more customizations.  I have added an implementation of this interface and the ability to set the wallpaper on a specific monitor.

With the 1.7 release the WallpaperChanger has a new option `-m` to designate setting the image on a specific monitor.  This is only available on Windows 8 and higher - other versions of Windows will simply return an error message.

Download the new version here: https://github.com/philhansen/WallpaperChanger/releases/tag/v1.7

Let me know if you encounter any issues.
